[neovim]
  type        = "git-repo"
  url         = "https://github.com/p3aga/nvim-config.git"
  targetPath  = ".config/nvim"

[notes]
  type        = "git-repo"
  url         = "https://github.com/p3aga/notes.git"
  targetPath  = ".notes"