[general]
import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[window]
dimensions = { columns = 80, lines = 22 }
padding = { x = 4, y = 8 }
decorations = "None"

[font]
normal = { family = "Cascadia Code NF", style = "Regular" }
size = 11

[cursor]
style = { shape = "Beam", blinking = "Off" }
